"""Shell completion generation for mailhub."""

from __future__ import annotations

import argparse
import sys
from typing import Sequence


# All mailhub subcommands
MAILHUB_SUBCOMMANDS = (
    "init", "auth", "status", "doctor", "reauth", "logout", "serve", "mcp", "config"
)

# All mailhub config subcommands
CONFIG_SUBCOMMANDS = (
    "list", "add-account", "validate", "doctor", "setup-google", "setup-microsoft", "remove-account"
)

# All mail subcommands
MAIL_SUBCOMMANDS = (
    "accounts", "folders", "search", "get", "send", "draft"
)

# Global flags for mailhub
MAILHUB_GLOBAL_FLAGS = (
    "--config", "--state", "--host", "--port"
)

# Config add-account flags
CONFIG_ADD_ACCOUNT_FLAGS = (
    "--alias", "--provider", "--capabilities", "--email"
)

# Mail flags
MAIL_FLAGS = (
    "--url", "--token", "--ro", "--json", "--confirm", "--config", "--state"
)


def generate_bash_completion() -> str:
    """Generate bash completion script."""
    return f'''# mailhub bash completion
# Generated by mailhub --generate-completion bash

_mailhub() {{
    local cur prev words cword
    _init_completion || return

    local mailhub_commands="{' '.join(MAILHUB_SUBCOMMANDS)}"
    local config_commands="{' '.join(CONFIG_SUBCOMMANDS)}"
    local mail_commands="{' '.join(MAIL_SUBCOMMANDS)}"
    local global_flags="{' '.join(MAILHUB_GLOBAL_FLAGS)}"
    local config_add_flags="{' '.join(CONFIG_ADD_ACCOUNT_FLAGS)}"
    local mail_flags="{' '.join(MAIL_FLAGS)}"

    case $prev in
        mailhub)
            COMPREPLY=($(compgen -W "$mailhub_commands" -- "$cur"))
            return 0
            ;;
        config)
            COMPREPLY=($(compgen -W "$config_commands" -- "$cur"))
            return 0
            ;;
        mail)
            COMPREPLY=($(compgen -W "$mail_commands" -- "$cur"))
            return 0
            ;;
        --config|--state|--host|--port)
            # These take arguments, don't complete
            return 0
            ;;
        --alias|--provider|--capabilities|--email)
            return 0
            ;;
        --url|--token|--ro|--json|--confirm|--config|--state)
            return 0
            ;;
    esac

    case $cur in
        -*)
            COMPREPLY=($(compgen -W "$global_flags" -- "$cur"))
            ;;
        *)
            if [[ $cword -eq 1 ]]; then
                COMPREPLY=($(compgen -W "$mailhub_commands" -- "$cur"))
            elif [[ $cword -eq 2 && ${{words[1]}} == "config" ]]; then
                COMPREPLY=($(compgen -W "$config_commands" -- "$cur"))
            elif [[ $cword -eq 2 && ${{words[1]}} == "mail" ]]; then
                COMPREPLY=($(compgen -W "$mail_commands" -- "$cur"))
            elif [[ $cword -ge 2 && ${{words[1]}} == "config" && ${{words[2]}} == "add-account" ]]; then
                COMPREPLY=($(compgen -W "$config_add_flags" -- "$cur"))
            elif [[ $cword -ge 2 && ${{words[1]}} == "mail" ]]; then
                COMPREPLY=($(compgen -W "$mail_flags" -- "$cur"))
            fi
            ;;
    esac
}}

complete -F _mailhub mailhub
complete -F _mailhub mail  # mail command uses same completion
'''

def generate_zsh_completion() -> str:
    """Generate zsh completion script."""
    return f'''# mailhub zsh completion
# Generated by mailhub --generate-completion zsh

#compdef mailhub mail

_mailhub() {{
    local context state state_descr line
    declare -A opt_args

    local mailhub_commands=({' '.join(MAILHUB_SUBCOMMANDS)})
    local config_commands=({' '.join(CONFIG_SUBCOMMANDS)})
    local mail_commands=({' '.join(MAIL_SUBCOMMANDS)})
    local global_flags=({' '.join(MAILHUB_GLOBAL_FLAGS)})
    local config_add_flags=({' '.join(CONFIG_ADD_ACCOUNT_FLAGS)})
    local mail_flags=({' '.join(MAIL_FLAGS)})

    _arguments -C \
        '(-h --help)'{{-h,--help}}'[Show help]' \
        '(-c --config)'{{-c,--config}}'[Config file path]:file:_files' \
        '(-s --state)'{{-s,--state}}'[State file path]:file:_files' \
        '(-h --host)'{{-h,--host}}'[Bind address]:string' \
        '(-p --port)'{{-p,--port}}'[Port number]:int' \
        ':command:($mailhub_commands)' \
        '*:: :->subcmds'

    case $state in
        (config)
            _arguments -C \
                ':subcommand:($config_commands)' \
                '*:: :->config_subcmd'
            ;;
        (mail)
            _arguments -C \
                ':subcommand:($mail_commands)' \
                '*:: :->mail_subcmd'
            ;;
    esac

    case $state in
        (config_add-account)
            _arguments \
                ${{config_add_flags}}
            ;;
        (mail_send|mail_draft)
            _arguments \
                ${{mail_flags}}
            ;;
    esac
}}

compdef _mailhub mailhub
compdef _mailhub mail
'''

def generate_fish_completion() -> str:
    """Generate fish completion script."""
    return f'''# mailhub fish completion
# Generated by mailhub --generate-completion fish

function __fish_mailhub_commands
    echo {' '.join(MAILHUB_SUBCOMMANDS)}
end

function __fish_mailhub_config_commands
    echo {' '.join(CONFIG_SUBCOMMANDS)}
end

function __fish_mailhub_mail_commands
    echo {' '.join(MAIL_SUBCOMMANDS)}
end

function __fish_mailhub_global_flags
    echo {' '.join(MAILHUB_GLOBAL_FLAGS)}
end

function __fish_mailhub_config_add_flags
    echo {' '.join(CONFIG_ADD_ACCOUNT_FLAGS)}
end

function __fish_mailhub_mail_flags
    echo {' '.join(MAIL_FLAGS)}
end

complete -c mailhub -f -a "(__fish_mailhub_commands)" -d "Mailhub administration commands"
complete -c mailhub -n "__fish_mailhub_using_command" -a "(__fish_mailhub_config_commands)" -d "Config subcommands"
complete -c mailhub -n "__fish_mailhub_using_command" -a "(__fish_mailhub_mail_commands)" -d "Mail subcommands"

complete -c mailhub -n "__fish_mailhub_using_flag" -a "(__fish_mailhub_global_flags)" -d "Global flags"

# Config add-account flags
complete -c mailhub -n "__fish_seen_subcommand_from config add-account" -a "(__fish_mailhub_config_add_flags)"

# Mail flags
complete -c mailhub -n "__fish_seen_subcommand_from mail" -a "(__fish_mailhub_mail_flags)"

# Also complete mail command
complete -c mail -f -a "(__fish_mailhub_mail_commands)"
complete -c mail -n "__fish_mailhub_using_flag" -a "(__fish_mailhub_mail_flags)"
'''


def generate_completion(shell: str) -> str:
    """Generate completion script for the given shell."""
    if shell == "bash":
        return generate_bash_completion()
    elif shell == "zsh":
        return generate_zsh_completion()
    elif shell == "fish":
        return generate_fish_completion()
    else:
        raise ValueError(f"Unsupported shell: {shell}")


def main() -> int:
    import argparse
    parser = argparse.ArgumentParser(description="Generate shell completions for mailhub")
    parser.add_argument("shell", choices=("bash", "zsh", "fish"), help="Target shell")
    args = parser.parse_args()
    
    try:
        script = generate_completion(args.shell)
        print(script)
        return 0
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
